# Site settings
title: Hassan and Associates
email: info@hassanandassociates.biz
description: > # this means to ignore newlines until "baseurl:"
  A Blog Site for Income tax, Company law and Business Service matters
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: hasanassociates
github_username:  
facebook_username: hassanandassociates.biz
google_play: 
google_plus_com: # Community link
google_plus_per:  #Personal link
facebook_app_id: 

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Official Site
    link: https://hassanandassociates.biz
  option2:
    name: Official Blog
    link: https://blog.hassanandassociates.biz
  option3:
    name: Diary Blog
    link: https://diary.hassanandassociates.biz

disqus: true
disqus_shortname: 'hassanandassociates'

# Build settings
markdown: kramdown
